// Run with installed Playwright or PLAYWRIGHT_MODULE=/path/to/playwright/index.mjs.
import assert from 'node:assert/strict';
const { chromium } = await import(process.env.PLAYWRIGHT_MODULE || 'playwright');
const browser = await chromium.launch({ headless: true, ...(process.env.CHROME_PATH ? { executablePath: process.env.CHROME_PATH } : {}) });
const url = process.env.PROTOTYPE_URL || 'http://127.0.0.1:4321';
const errors = [];
try {
  const context = await browser.newContext({ viewport: { width: 1512, height: 1100 }, reducedMotion: 'reduce' });
  const page = await context.newPage();
  page.on('pageerror', e => errors.push(e.message));
  page.on('console', m => { if (m.type() === 'error') errors.push(m.text()); });
  await page.goto(url);
  const utility = async id => {
    if (!await page.locator(`#${id}`).isVisible()) {
      if (['source-info','reset'].includes(id)) await page.locator('#toggle-sidebar').click();
      else await page.locator('#desk-menu > summary').click();
    }
    await page.locator(`#${id}`).click();
  };
  assert.equal(await page.locator('.note-card').count(), 20);
  assert.equal(await page.locator('#inspector').isVisible(), false);
  await page.locator('[data-open="n1"]').click();
  assert.equal(await page.locator('#inspector h2').textContent(), 'A place to wander');
  assert.equal(await page.locator('[data-view="notebook"], [data-view="graph"]').count(), 0);
  // Visible Connect -> searchable chooser -> two-way connection.
  if (!await page.locator('#inspector').isVisible()) await page.locator('[data-read]').click();
  await page.locator('#connect-note').click();
  assert.match(await page.locator('#picker-context').textContent(), /A place to wander/);
  assert.equal(await page.locator('[data-pick="n1"], [data-pick="n2"]').count(), 0, 'Self and existing links excluded');
  await page.locator('#picker-search').fill('Leave a trail');
  await page.locator('#picker-search').press('Enter');
  assert.equal(await page.locator('#inspector [data-hop="n20"]').count(), 1);
  await page.locator('#inspector [data-hop="n20"]').click();
  assert.equal(await page.locator('.chain-focus h2').textContent(), 'Leave a trail for tomorrow');
  assert.equal(await page.locator('#inspector [data-hop="n1"]').count(), 1);
  await page.locator('#back').click();
  assert.equal(await page.locator('.chain-focus h2').textContent(), 'A place to wander');
  await page.locator('#forward').click();
  assert.equal(await page.locator('.chain-focus h2').textContent(), 'Leave a trail for tomorrow');
  await page.locator('#back').click();
  await page.locator('.branch-card[data-hop="n2"]').click();
  assert.equal(await page.locator('#forward').isDisabled(), true, 'New branch truncates forward navigation');
  // New thought can be created and connected atomically, with tag chips.
  if (!await page.locator('#inspector').isVisible()) await page.locator('[data-read]').click();
  await page.locator('#connect-note').click();
  await page.locator('#picker-search').fill('Fresh linked sample');
  assert.equal(await page.locator('.picker-empty').count(), 1);
  await page.locator('#new-linked').click();
  assert.equal(await page.locator('[name="freeTitle"]').inputValue(), 'Fresh linked sample');
  await page.locator('[name="body"]').fill('Only sample data.');
  await page.locator('#capture-details summary').click();
  await page.locator('#tag-input').fill('#Test, learning');
  await page.locator('#tag-input').press('Enter');
  assert.equal(await page.locator('#editing-tags button').count(), 2);
  await page.locator('#tag-input').fill('test');
  await page.locator('#add-tag').click();
  assert.equal(await page.locator('#editing-tags button').count(), 2, 'Tags deduplicate');
  await page.keyboard.press('Control+s');
  assert.equal(await page.locator('#editor-dialog').isVisible(), false);
  assert.equal(await page.locator('.chain-focus h2').textContent(), 'Fresh linked sample');
  assert.equal(await page.locator('#inspector [data-hop="n2"]').count(), 1);
  await page.reload();
  assert.equal(await page.locator('.note-card').count(), 21);
  // Cmd+F finds globally even with an unrelated collection filter.
  await page.locator('#toggle-sidebar').click();
  await page.locator('#collections [data-topic="Wardrub"]').click();
  assert.equal(await page.locator('.note-card').count(), 4);
  await page.keyboard.press('Meta+f');
  assert.equal(await page.locator('#picker-dialog').isVisible(), true);
  await page.locator('#picker-search').fill('Fresh linked');
  await page.locator('#picker-search').press('Enter');
  assert.equal(await page.locator('.chain-focus h2').textContent(), 'Fresh linked sample');
  await page.locator('#all-cards').click();
  assert.equal(await page.locator('.note-card').count(), 4, 'Desk filters preserved during exploration');
  await page.locator('#clear-filter').click();
  // Tags action opens exactly the right field; drafts cancel safely.
  await page.locator('[data-open]').first().click();
  await page.keyboard.press('f');
  await page.locator('#picker-search').fill('Fresh linked'); await page.locator('#picker-search').press('Enter');
  await page.locator('[data-read]').click();
  await page.locator('#inspector [data-tags]').first().click();
  assert.equal(await page.locator('#tag-input').evaluate(el => el === document.activeElement), true);
  await page.locator('[data-remove-tag="test"]').click();
  await page.locator('[name="freeTitle"]').fill('Revised sample');
  await page.locator('[name="body"]').fill('<script>window.BAD=true</script>\n\nA safe, edited note.');
  await page.keyboard.press('Meta+s');
  assert.equal(await page.locator('#inspector h2').textContent(), 'Revised sample');
  assert.equal(await page.evaluate(() => window.BAD), undefined);
  await page.reload();
  await page.keyboard.press('Control+f');
  await page.locator('#picker-search').fill('Revised sample');
  await page.locator('#picker-search').press('Enter');
  assert.equal(await page.locator('#inspector [data-tag="test"]').count(), 0);
  assert.equal(await page.locator('#inspector [data-tag="learning"]').count(), 1);
  // Remove/undo, with reverse link checked.
  await page.locator('[data-read]').click();
  await page.locator('#inspector [data-unlink="n2"]').click();
  assert.equal(await page.locator('#inspector [data-hop="n2"]').count(), 0);
  await utility('undo');
  assert.equal(await page.locator('#inspector [data-hop="n2"]').count(), 1);
  // An unselected card's Connect action uses that card, not the reader selection.
  await page.locator('#all-cards').click();
  await page.locator('.note-card [data-connect="n6"]').click();
  assert.match(await page.locator('#picker-context').textContent(), /Clothes, not catalogues/);
  await page.keyboard.press('Escape');
  // Keyboard picker and plain N work; shortcuts do not hijack text fields.
  await page.locator('#find-note').click();
  await page.locator('#picker-search').press('ArrowDown');
  assert.equal(await page.locator('#picker-search').getAttribute('aria-activedescendant'), 'pick-1');
  await page.keyboard.press('Escape');
  await page.locator('.card-open').first().focus();
  await page.keyboard.press('ArrowRight');
  assert.equal(await page.evaluate(() => document.activeElement.dataset.open), await page.locator('.card-open').nth(1).getAttribute('data-open'));
  await page.keyboard.press('Enter');
  await page.keyboard.press('n');
  assert.equal(await page.locator('#editor-dialog').isVisible(), true);
  await page.locator('#compose-mode').selectOption('structured');
  await page.locator('[name="title"]').fill('Typing n e t c should stay text');
  await page.locator('[name="title"]').press('n');
  assert.equal(await page.locator('#picker-dialog').isVisible(), false);
  await page.keyboard.press('Escape');
  assert.equal(await page.locator('.note-card').count(), 21, 'Cancelled draft not saved');
  await page.locator('#toggle-sidebar').click();
  await page.locator('#search').fill('nothing-matches-this'); await page.locator('#close-sidebar').click();
  assert.equal(await page.locator('.empty-state').count(), 1);
  await page.locator('#empty-clear').click();
  await page.locator('[data-view="cloud"]').click();
  await page.locator('#cloud [data-cloud-tag="thoughtos"]').click();
  assert.equal(await page.locator('.note-card').count(), 4);
  await page.locator('[data-view="desk"]').click();
  // Reset and screenshot default desk and branch exploration.
  page.once('dialog', d => d.accept()); await utility('reset'); await page.locator('#close-sidebar').click();
  await page.screenshot({ path: '/tmp/thoughtos-desk-v3.png', fullPage: true });
  await page.locator('.note-card [data-explore="n1"]').first().click();
  assert.equal(await page.locator('.branch-card').count(), 4);
  assert.ok(await page.locator('.nearby-card').count() > 0);
  const target = await page.locator('.suggest-connect').first().getAttribute('data-suggest-connect');
  await page.locator('.suggest-connect').first().click();
  await page.locator(`[data-pick="${target}"]`).click();
  assert.equal(await page.locator(`.branch-card[data-hop="${target}"]`).count(), 1);
  await utility('undo');
  assert.equal(await page.locator(`.branch-card[data-hop="${target}"]`).count(), 0);
  await page.screenshot({ path: '/tmp/thoughtos-chain-v3.png', fullPage: true });
  if (!await page.locator('#inspector').isVisible()) await page.locator('[data-read]').click();
  await page.locator('#connect-note').click();
  await page.screenshot({ path: '/tmp/thoughtos-connect-v3.png' });
  await page.keyboard.press('Escape');
  await utility('source-info');
  assert.match(await page.locator('#sources-dialog').textContent(), /Obsidian/);
  await page.keyboard.press('Escape'); await page.locator('#close-sidebar').click();
  // Server remains static and cannot expose live data or accept writes.
  for (const path of ['/context_os.db', '/.env', '/README.md']) assert.equal((await context.request.get(url + path)).status(), 404);
  assert.equal((await context.request.post(url + '/')).status(), 405);
  const mobile = await browser.newContext({ viewport: { width: 390, height: 844 }, isMobile: true, hasTouch: true, reducedMotion: 'reduce' });
  const phone = await mobile.newPage(); phone.on('pageerror', e => errors.push(e.message));
  await phone.goto(url);
  assert.ok(await phone.evaluate(() => document.documentElement.scrollWidth <= innerWidth), 'No mobile horizontal overflow');
  await phone.locator('.note-card [data-connect="n6"]').click();
  await phone.locator('#picker-search').fill('Leave a trail');
  await phone.locator('[data-pick="n20"]').click();
  assert.equal(await phone.locator('#inspector h2').textContent(), 'Clothes, not catalogues');
  await phone.locator('#inspector [data-hop="n20"]').click();
  assert.ok(await phone.evaluate(() => document.documentElement.scrollWidth <= innerWidth), 'No chain overflow');
  await phone.screenshot({ path: '/tmp/thoughtos-mobile-chain-v3.png', fullPage: true });
  await phone.evaluate(() => localStorage.setItem('thoughtos.visual-garden.v1', '{bad json'));
  await phone.reload();
  assert.equal(await phone.locator('#storage-warning').isVisible(), true);
  assert.equal(await phone.evaluate(() => localStorage.getItem('thoughtos.visual-garden.v1')), '{bad json');
  assert.deepEqual(errors, [], 'No browser runtime or console errors');
  console.log('PASS: desk, connect picker, reciprocal links, chain branching/back/forward, tag chips, global search, shortcuts, persistence, undo, mobile and server isolation');
} finally { await browser.close(); }
